{"name": "test_4应急取款失败", "status": "passed", "description": "应急取款失败", "start": 1571911380954, "stop": 1571911381014, "uuid": "84755f3f-3ebd-4248-aea2-fbf83d6bfc16", "historyId": "42dc1c25ec095052b5151b5c6511d239", "testCaseId": "8acfd169575689867af126ce19e226d9", "fullName": "建投自动化测试.现金管理测试用例.test_现金管理-添鑫宝-应急取款.Test_现金管理_添鑫宝_应急取款#test_4应急取款失败", "labels": [{"name": "story", "value": "应急取款失败"}, {"name": "feature", "value": "现金管理-添鑫宝-应急取款用例"}, {"name": "tag", "value": "cashmanage"}, {"name": "parentSuite", "value": "建投自动化测试.现金管理测试用例"}, {"name": "suite", "value": "test_现金管理-添鑫宝-应急取款"}, {"name": "subSuite", "value": "Test_现金管理_添鑫宝_应急取款"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "8061-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "建投自动化测试.现金管理测试用例.test_现金管理-添鑫宝-应急取款"}]}